var pages = require('./pages');
var common = require('./common');
var connection = require('./connection');
var actors = require('./actors');
var auto = require('./auto');
var assistance = require('./assistance');
var loan = require('./loan');
var savings = require('./savings');
var receipt = require('./receipt');
var payment = require('./payment');
var payback = require('./payback');
var admin = require('./admin');
var print = require('./print');
var premium = require('./premium');
var mySpace = require('./mySpace');
var configs = require('./configs');
var smsapi = require('./smsapi');
var msg = require('./msg');
exports.declare = function (app) {
  pages.declare(app);
  common.declare(app);
  connection.declare(app);
  actors.declare(app);
  auto.declare(app);
  assistance.declare(app);
  loan.declare(app);
  savings.declare(app);
  receipt.declare(app);
  payment.declare(app);
  payback.declare(app);
  admin.declare(app);
  print.declare(app);
  premium.declare(app);
  mySpace.declare(app);
  configs.declare(app);
  smsapi.declare(app);
  msg.declare(app);
};
