db.assistance.country.insert({name: 'ACORES', zone: 1})
db.assistance.country.insert({name: 'AFRIQUE DU SUD', zone: 1})
db.assistance.country.insert({name: 'ALASKA', zone: 2})
db.assistance.country.insert({name: 'ALBANIE', zone: 1})
db.assistance.country.insert({name: 'ALGERIE', zone: 1})
db.assistance.country.insert({name: 'ALLEMAGNE', zone: 1})
db.assistance.country.insert({name: 'ANDORRE', zone: 1})
db.assistance.country.insert({name: 'ANGOLA', zone: 1})
db.assistance.country.insert({name: 'ANTILLES', zone: 1})
db.assistance.country.insert({name: 'ARABIE SAOUDITE', zone: 1})
db.assistance.country.insert({name: 'ARGENTINE', zone: 1})
db.assistance.country.insert({name: 'ARMENIE', zone: 1})
db.assistance.country.insert({name: 'AUSTRALIE', zone: 2})
db.assistance.country.insert({name: 'AUTRICHE', zone: 1})
db.assistance.country.insert({name: 'AZERBAIDJAN', zone: 1})
db.assistance.country.insert({name: 'BAHAMAS', zone: 1})
db.assistance.country.insert({name: 'BAHREIN', zone: 1})
db.assistance.country.insert({name: 'BALEARES', zone: 1})
db.assistance.country.insert({name: 'BALI', zone: 1})
db.assistance.country.insert({name: 'BANGLADESH', zone: 1})
db.assistance.country.insert({name: 'BARBADE', zone: 1})
db.assistance.country.insert({name: 'BELGIQUE', zone: 1})
db.assistance.country.insert({name: 'BENIN', zone: 1})
db.assistance.country.insert({name: 'BERMUDES', zone: 1})
db.assistance.country.insert({name: 'BIELORUSSIE', zone: 1})
db.assistance.country.insert({name: 'BOLIVIE', zone: 1})
db.assistance.country.insert({name: 'BORNEO', zone: 1})
db.assistance.country.insert({name: 'BOSNIE', zone: 1})
db.assistance.country.insert({name: 'BOTSWANA', zone: 1})
db.assistance.country.insert({name: 'BRESIL', zone: 1})
db.assistance.country.insert({name: 'BULGARIE', zone: 1})
db.assistance.country.insert({name: 'BURKINA FASO', zone: 1})
db.assistance.country.insert({name: 'BURUNDI', zone: 1})
db.assistance.country.insert({name: 'CAMBODGE', zone: 1})
db.assistance.country.insert({name: 'CAMROUN', zone: 1})
db.assistance.country.insert({name: 'CANADA', zone: 2})
db.assistance.country.insert({name: 'CANARIE', zone: 1})
db.assistance.country.insert({name: 'CANGO', zone: 1})
db.assistance.country.insert({name: 'CAP-VERT', zone: 1})
db.assistance.country.insert({name: 'CHILI', zone: 1})
db.assistance.country.insert({name: 'CHINE', zone: 1})
db.assistance.country.insert({name: 'CHYPRE', zone: 1})
db.assistance.country.insert({name: 'COLOMBIE', zone: 1})
db.assistance.country.insert({name: 'COMORES', zone: 1})
db.assistance.country.insert({name: 'CONGO', zone: 1})
db.assistance.country.insert({name: 'CORE', zone: 1})
db.assistance.country.insert({name: 'COSTA-RICA', zone: 1})
db.assistance.country.insert({name: 'COTE D\'IVOIRE', zone: 1})
db.assistance.country.insert({name: 'CROATIE', zone: 1})
db.assistance.country.insert({name: 'CUBA', zone: 1})
db.assistance.country.insert({name: 'DANEMARK', zone: 1})
db.assistance.country.insert({name: 'DJIBOUTI', zone: 1})
db.assistance.country.insert({name: 'DOMINIQUE', zone: 1})
db.assistance.country.insert({name: 'EGYPTE', zone: 1})
db.assistance.country.insert({name: 'EMIRATS ARABE', zone: 1})
db.assistance.country.insert({name: 'EQUATEUR', zone: 1})
db.assistance.country.insert({name: 'ESPAGNE', zone: 1})
db.assistance.country.insert({name: 'ESTONIE', zone: 1})
db.assistance.country.insert({name: 'ETATS UNIS D\'AMERIQUE', zone: 2})
db.assistance.country.insert({name: 'ETHIOPIE', zone: 1})
db.assistance.country.insert({name: 'EUROPE', zone: 1})
db.assistance.country.insert({name: 'FIDJI', zone: 1})
db.assistance.country.insert({name: 'FINLANDE', zone: 1})
db.assistance.country.insert({name: 'FRANCE', zone: 1})
db.assistance.country.insert({name: 'GABON', zone: 1})
db.assistance.country.insert({name: 'GAMBIE', zone: 1})
db.assistance.country.insert({name: 'GEORGIE', zone: 1})
db.assistance.country.insert({name: 'GHANA', zone: 1})
db.assistance.country.insert({name: 'GIBRALTAR', zone: 1})
db.assistance.country.insert({name: 'GRANDE BRETAGNE', zone: 1})
db.assistance.country.insert({name: 'GRECE', zone: 1})
db.assistance.country.insert({name: 'GRENADE', zone: 1})
db.assistance.country.insert({name: 'GROENLAND', zone: 1})
db.assistance.country.insert({name: 'GUATEMALA', zone: 1})
db.assistance.country.insert({name: 'GUINEE', zone: 1})
db.assistance.country.insert({name: 'GUYANE', zone: 1})
db.assistance.country.insert({name: 'HAITI', zone: 1})
db.assistance.country.insert({name: 'HAWAI', zone: 1})
db.assistance.country.insert({name: 'HOLLANDE', zone: 1})
db.assistance.country.insert({name: 'HONDURAS', zone: 1})
db.assistance.country.insert({name: 'HONG KONG', zone: 1})
db.assistance.country.insert({name: 'HONGRIE', zone: 1})
db.assistance.country.insert({name: 'IKRAINE', zone: 1})
db.assistance.country.insert({name: 'INDE', zone: 1})
db.assistance.country.insert({name: 'INDONISIE', zone: 1})
db.assistance.country.insert({name: 'IRAK', zone: 1})
db.assistance.country.insert({name: 'IRAN', zone: 1})
db.assistance.country.insert({name: 'IRLANDE', zone: 1})
db.assistance.country.insert({name: 'ISLANDE', zone: 1})
db.assistance.country.insert({name: 'ISRAEL', zone: 1})
db.assistance.country.insert({name: 'ITALIE', zone: 1})
db.assistance.country.insert({name: 'JAMAIQUE', zone: 1})
db.assistance.country.insert({name: 'JAPON', zone: 2})
db.assistance.country.insert({name: 'JAVA', zone: 1})
db.assistance.country.insert({name: 'JORDANIE', zone: 1})
db.assistance.country.insert({name: 'KAZAKHSTAN', zone: 1})
db.assistance.country.insert({name: 'KENYA', zone: 1})
db.assistance.country.insert({name: 'KIRGHIZISTAN', zone: 1})
db.assistance.country.insert({name: 'KOWEIT', zone: 1})
db.assistance.country.insert({name: 'LAOS', zone: 1})
db.assistance.country.insert({name: 'LETTONIE', zone: 1})
db.assistance.country.insert({name: 'LIBAN', zone: 1})
db.assistance.country.insert({name: 'LIBIRIA', zone: 1})
db.assistance.country.insert({name: 'LIECHTENSTEIN', zone: 1})
db.assistance.country.insert({name: 'LITUANIE', zone: 1})
db.assistance.country.insert({name: 'LUXEMBOURG', zone: 1})
db.assistance.country.insert({name: 'LYBIE', zone: 1})
db.assistance.country.insert({name: 'MACEDOINE', zone: 1})
db.assistance.country.insert({name: 'MADAGASCAR', zone: 1})
db.assistance.country.insert({name: 'MADERE', zone: 1})
db.assistance.country.insert({name: 'MALAISIE', zone: 1})
db.assistance.country.insert({name: 'MALAWI', zone: 1})
db.assistance.country.insert({name: 'MALDIVES', zone: 1})
db.assistance.country.insert({name: 'MALI', zone: 1})
db.assistance.country.insert({name: 'MALTE', zone: 1})
db.assistance.country.insert({name: 'MAROC', zone: 1})
db.assistance.country.insert({name: 'MAURICE', zone: 1})
db.assistance.country.insert({name: 'MAURITANIE', zone: 1})
db.assistance.country.insert({name: 'MEXIQUE', zone: 1})
db.assistance.country.insert({name: 'MOLDAVIE', zone: 1})
db.assistance.country.insert({name: 'MOLUQUES', zone: 1})
db.assistance.country.insert({name: 'MONACO', zone: 1})
db.assistance.country.insert({name: 'MONDE ENTIER', zone: 2})
db.assistance.country.insert({name: 'MONGOLIE', zone: 1})
db.assistance.country.insert({name: 'MOZANBIQUE', zone: 1})
db.assistance.country.insert({name: 'MYANMAR', zone: 1})
db.assistance.country.insert({name: 'NAMIBIE', zone: 1})
db.assistance.country.insert({name: 'NEPAL', zone: 1})
db.assistance.country.insert({name: 'NIGER', zone: 1})
db.assistance.country.insert({name: 'NIGERIA', zone: 1})
db.assistance.country.insert({name: 'NORVEGE', zone: 1})
db.assistance.country.insert({name: 'NOUVELLE CALEDONIE', zone: 1})
db.assistance.country.insert({name: 'NOUVELLE ZELANDE', zone: 1})
db.assistance.country.insert({name: 'OMAN', zone: 1})
db.assistance.country.insert({name: 'OUZBEKISTAN', zone: 1})
db.assistance.country.insert({name: 'PAKISTAN', zone: 1})
db.assistance.country.insert({name: 'PANAMA', zone: 1})
db.assistance.country.insert({name: 'PAPOUASIE', zone: 1})
db.assistance.country.insert({name: 'PARAGUAY', zone: 1})
db.assistance.country.insert({name: 'PAYS-BAS', zone: 1})
db.assistance.country.insert({name: 'PEROU', zone: 1})
db.assistance.country.insert({name: 'PHILIPPINES', zone: 1})
db.assistance.country.insert({name: 'POLOGNE', zone: 1})
db.assistance.country.insert({name: 'POLYNESIE', zone: 1})
db.assistance.country.insert({name: 'PORTORICO', zone: 1})
db.assistance.country.insert({name: 'PORTUGAL', zone: 1})
db.assistance.country.insert({name: 'QUATAR', zone: 1})
db.assistance.country.insert({name: 'REBUBLIQUE CENTRAFRICAINE', zone: 1})
db.assistance.country.insert({name: 'RENION', zone: 1})
db.assistance.country.insert({name: 'REPUBLIQUE DOMINICAINE', zone: 1})
db.assistance.country.insert({name: 'REPUBLIQUE TCHEQUE', zone: 1})
db.assistance.country.insert({name: 'ROUMANIE', zone: 1})
db.assistance.country.insert({name: 'RUSSIE', zone: 1})
db.assistance.country.insert({name: 'RUSSIE (PARTIE ASIATIQUE)', zone: 1})
db.assistance.country.insert({name: 'RWANDA', zone: 1})
db.assistance.country.insert({name: 'SAINT PIERRE ET MIQUELON', zone: 1})
db.assistance.country.insert({name: 'SAINT-VINCENT (GRENADINE)', zone: 1})
db.assistance.country.insert({name: 'SAINTE-LUCIE', zone: 1})
db.assistance.country.insert({name: 'SAN MARIN', zone: 1})
db.assistance.country.insert({name: 'SENEGAL', zone: 1})
db.assistance.country.insert({name: 'SERBIE', zone: 1})
db.assistance.country.insert({name: 'SEYCHELLES', zone: 1})
db.assistance.country.insert({name: 'SIERRA-LEONE', zone: 1})
db.assistance.country.insert({name: 'SINGAPOUR', zone: 1})
db.assistance.country.insert({name: 'SLOVAQUIE', zone: 1})
db.assistance.country.insert({name: 'SLOVENIE', zone: 1})
db.assistance.country.insert({name: 'SOUDAN', zone: 1})
db.assistance.country.insert({name: 'SOUMALIE', zone: 1})
db.assistance.country.insert({name: 'SRI LANKA', zone: 1})
db.assistance.country.insert({name: 'SUEDE', zone: 1})
db.assistance.country.insert({name: 'SUISSE', zone: 1})
db.assistance.country.insert({name: 'SUMATRA', zone: 1})
db.assistance.country.insert({name: 'SURINAM', zone: 1})
db.assistance.country.insert({name: 'SYRIE', zone: 1})
db.assistance.country.insert({name: 'TADJIKISTAN', zone: 1})
db.assistance.country.insert({name: 'TAIWAN', zone: 1})
db.assistance.country.insert({name: 'TANZANIE', zone: 1})
db.assistance.country.insert({name: 'TCHAD', zone: 1})
db.assistance.country.insert({name: 'THAILANDE', zone: 1})
db.assistance.country.insert({name: 'TOGO', zone: 1})
db.assistance.country.insert({name: 'TOUS LES PAYS (ZONE 1)', zone: 1})
db.assistance.country.insert({name: 'TRINIDAD ET TOBAGO', zone: 1})
db.assistance.country.insert({name: 'TURKMENISTAN', zone: 1})
db.assistance.country.insert({name: 'TURQUIE', zone: 1})
db.assistance.country.insert({name: 'UKRAINE', zone: 1})
db.assistance.country.insert({name: 'URUGUAY', zone: 1})
db.assistance.country.insert({name: 'VENEZUELA', zone: 1})
db.assistance.country.insert({name: 'VIERGES', zone: 1})
db.assistance.country.insert({name: 'VIETNAM', zone: 1})
db.assistance.country.insert({name: 'YEMEN', zone: 1})
db.assistance.country.insert({name: 'YOGOSLAVIE', zone: 1})
db.assistance.country.insert({name: 'ZAIRE', zone: 1})
db.assistance.country.insert({name: 'ZAMBIE', zone: 1})
db.assistance.country.insert({name: 'ZIMBABWE', zone: 1})