var coverReference = [{code: 'G01', name: 'RC-RTI'},
{code: 'G02', name: 'DRA - CAS'},
{code: 'G03', name: 'VOL'},
{code: 'G04', name: 'INCENDIE'},
{code: 'G06', name: 'DOMMAGES AUX VEHICULES'},
{code: 'G07', name: 'DOMMAGES-COLLISION'},
{code: 'G09', name: 'PERSONNES TRANSPORTEES ASSUREES'},
{code: 'G10', name: 'BRIS DE GLACES'},
{code: 'G11', name: 'VOL RK7'},
{code: 'G14', name: 'FORCE DE LA NATURE'},
{code: 'G16', name: 'CONDUCTEUR PLUS'},
{code: 'G17', name: 'ASSISTANCE AUTO PLUS'},
{code: 'G25', name: 'ASSISTANCE UTIL PLUS'},
{code: 'G28', name: 'ASSISTANCE GOLD'},
{code: 'G30', name: 'INCENDIE SUITE EMEUTES ET MOUVEMENTS POPULAIRE'},
{code: 'G34', name: 'DOMMAGES SUITE EMEUTES ET MOUVEMENTS POPULAIRE'},
{code: 'G39', name: 'ASSISTANCE ACCIDENT AUTO (3A)'},
{code: 'INC', name: 'INCENDIE'},
{code: 'RDS', name: 'RISQUES DIVERS'},
{code: 'TRP', name: 'TRANSPORT'},
{code: 'VIE', name: 'VIE'},
{code: 'SNT', name: 'SANTE'},
{code: 'ASV', name: 'ASSISTANCE EN VOYAGE'}];
db.common.coverReference.insert(coverReference);